### ISSUE TITLE
RateBeer search does not support ! in beer names

### ISSUE THREAD

**Issue by parryc** [OrganicIrradiation/ratebeer#39]
If you search for the (delicious) `Mikkeller George!`, RateBeer chokes and searches instead for `Mikkeller George&#033`, which returns nothing. Interestingly just searching for `George!` returns `Tarn 51 By George!`, so it's probably an issue with how they are storing/searching for the beer names.

It might be worthwhile to have an option for "searching-with-fixes" (toggle-able, of course).  That option would help construct searches that are a little bit more in line with what the user was hoping to search for.

Thoughts?

**Comment by parryc** [comment]
Here's the strip function I have in my wrapper program:

```python
def _dirtystrip(line):
    """
        Returns a RateBeer appropriate search string. Normalizes to get accents as
        individual characters and then strips them. ord < 256 allows characters like
        ø and ð to remain.

        Also strip / and !. RateBeer can't handle them. Man, their search seriously sucks.    
    """
    line = unicodedata.normalize('NFKD',line)
    line = line.replace('/',' ')
    line = line.replace('!',' ')
    return ''.join([x for x in line if ord(x) < 256])
```

**Comment by OrganicIrradiation** [comment]
Just tested on ratebeer.com and it looks like it certainly is an issue with their url encoding/decoding. Maybe raise a warning as well to note that a search has been "sanitized" due to incompatible characters?

**Comment by parryc** [comment]
This is no longer a problem after RateBeer switched to a React-based framework (see #48).
