### ISSUE TITLE
Create new pip repo?

### ISSUE THREAD

**Issue by parryc** [OrganicIrradiation/ratebeer#47]
Since it appears @alilja may be permanently AFK, do we want to make a new pip repo (either on my account or someone else's)?  We could bump the version up to 3 and call the package `ratebeer3`. Making sure to update all relevant documentation, of course. 

What do you think, @OrganicIrradiation?

**Comment by parryc** [comment]
Might also be worth getting Travis-CL set up to [run weekly](https://docs.travis-ci.com/user/cron-jobs/), to let us be more aware if RateBeer has any breaking changes (not sure if I have permissions to link between this repo and Travis though).

**Comment by OrganicIrradiation** [comment]
I reached out to @alilja via email, so hopefully he'd consider transferring ownership of the GitHub repo and/or the PyPI project so that they can be kept up-to-date. I'd rather not fork, if possible, but the project as-is does not work when installed via PyPI ```pip```.

**Comment by OrganicIrradiation** [comment]
@alilja has been super helpful and responsive and it looks like everything is getting transferred over so that active development can continue. @parryc, check your notifications, you should have push access to the repo now.

**Comment by alilja** [comment]
i for one welcome our new postdoc overlord

**Comment by parryc** [comment]
Awesome, thanks @OrganicIrradiation and @alilja!  @OrganicIrradiation, do you have access to the pip repo then?

**Comment by OrganicIrradiation** [comment]
@parryc, yes, I am now listed as an "owner" on PyPI, meaning I can push updates. Let me know if you'd also like access for more timely updates.

**Comment by parryc** [comment]
Sounds good, just making sure – and no need for access right now, thanks though.
